export const QUESTION_DATA = [
    // GODS
    { id: 1, q: "Who was the Roman god of war and the father of Romulus and Remus?", o: ["Apollo", "Jupiter", "Mars", "Pluto"], a: 2, cat: "Mythology", expl: "<strong>Mars</strong> is the god of war. He is the legendary father of Romulus and Remus." },
    { id: 2, q: "What Roman god was a blacksmith, son of Juno, husband to Venus, and was permanently injured as a child?", o: ["Vulcan", "Neptune", "Apollo", "Mercury"], a: 0, cat: "Mythology", expl: "<strong>Vulcan</strong> (Volcanus) is the god of the forge. He was thrown from Olympus, causing his limp." },
    { id: 3, q: "Which of the Roman gods, pictured with his three-headed dog, ruled the underworld?", o: ["Jupiter", "Neptune", "Vulcan", "Pluto"], a: 3, cat: "Mythology", expl: "<strong>Pluto</strong> rules the Underworld. The 3-headed dog is Cerberus." },
    { id: 4, q: "Who was the Roman goddess of wisdom, known to the Greeks as Athena?", o: ["Juno", "Minerva", "Venus", "Diana"], a: 1, cat: "Mythology", expl: "<strong>Minerva</strong> is the goddess of wisdom. Her Greek counterpart is Athena." },
    { id: 5, q: "I descend from Olympus to earth. I am a messenger and Roman god. Who am I? (winged shoes)", o: ["Mercurius", "Neptūnus", "Mars", "Apollō"], a: 0, cat: "Mythology", expl: "<strong>Mercurius</strong> (Mercury) is the messenger god, known for his winged sandals." },
    { id: 6, q: "Which woodland deity would a Roman call upon while hunting?", o: ["Mars", "Venus", "Bacchus", "Diana"], a: 3, cat: "Mythology", expl: "<strong>Diana</strong> is the goddess of the hunt, the moon, and animals." },
    { id: 7, q: "Who was the Roman goddess of marriage and the queen of the gods?", o: ["Minerva", "Vesta", "Diana", "Juno"], a: 3, cat: "Mythology", expl: "<strong>Juno</strong> is the queen of the gods and protects marriage." },
    { id: 8, q: "Venus was the goddess of _____.", o: ["wisdom", "home and hearth", "love and beauty", "hunting"], a: 2, cat: "Mythology", expl: "<strong>Venus</strong> is the goddess of Love and Beauty." },
    { id: 9, q: "Which god ruled the Underworld and possessed its mineral wealth?", o: ["Mars", "Mercury", "Pluto", "Apollo"], a: 2, cat: "Mythology", expl: "<strong>Pluto</strong> (from Greek 'Plouton' meaning wealth) rules the rich minerals underground." },
    { id: 10, q: "The three Olympian brothers whose realms were the sky, the Underworld, and the seas were Jupiter, Pluto, and _____.", o: ["Mars", "Neptune", "Apollo", "Vulcan"], a: 1, cat: "Mythology", expl: "<strong>Neptune</strong> rules the Sea. Jupiter rules the Sky. Pluto rules the Underworld." },
    { id: 11, q: "Ceres, mother of Proserpina, was the goddess of:", o: ["love", "wisdom", "hunting", "agriculture"], a: 3, cat: "Mythology", expl: "<strong>Ceres</strong> is the goddess of Agriculture (grain)." },
    { id: 12, q: "Quis est frater Diānae? (Who is the brother of Diana?)", o: ["Apollō", "Plūtō", "Mercurius", "Neptūnus"], a: 0, cat: "Mythology", expl: "<strong>Apollo</strong> (Sun) and Diana (Moon) are twins." },
    { id: 13, q: "What Roman god of music was often seen with a lyre?", o: ["Mars", "Mercury", "Apollo", "Vulcan"], a: 2, cat: "Mythology", expl: "<strong>Apollo</strong> is the god of music, poetry, and prophecy." },
    { id: 14, q: "Quis est pater Minervae? (Who is the father of Minerva?)", o: ["Iuppiter", "Neptūnus", "Saturnus", "Plūtō"], a: 0, cat: "Mythology", expl: "<strong>Jupiter</strong> is the father. Minerva was born from his head." },
    { id: 15, q: "The peacock is the symbol of which goddess?", o: ["Minerva", "Juno", "Diana", "Vesta"], a: 1, cat: "Mythology", expl: "The peacock is the sacred bird of <strong>Juno</strong>." },
    { id: 16, q: "What is the Roman name for the Greek god Hermes?", o: ["Mercury", "Mars", "Vulcan", "Pluto"], a: 0, cat: "Mythology", expl: "Hermes is <strong>Mercury</strong>." },
    { id: 17, q: "Which goddess is the mother of Cupid and has the dove as a symbol?", o: ["Juno", "Venus", "Minerva", "Vesta"], a: 1, cat: "Mythology", expl: "<strong>Venus</strong> (Love) is the mother of Cupid." },

    // GEOGRAPHY
    { id: 18, q: "Ubi est Aegyptus (Egypt) in chartā geographicā?", o: ["(Map Position 1)", "(Map Position 2)", "South-East Corner", "(Map Position 4)"], a: 2, cat: "Geography", expl: "Egypt (Aegyptus) is in the bottom right (South-East) corner of the Roman map." },
    { id: 19, q: "Which location on the map does NOT border Mare Nostrum (Mediterranean)?", o: ["Hispania", "Italia", "Graecia", "Germania"], a: 3, cat: "Geography", expl: "<strong>Germania</strong> (Germany) is north, bordering the Rhine, not the Mediterranean." },
    { id: 20, q: "Identify the province acquired through warfare with Celtic/Gallic people (France).", o: ["Gallia", "Graecia", "Aegyptus", "Asia"], a: 0, cat: "Geography", expl: "<strong>Gallia</strong> (Gaul) is modern-day France." },
    { id: 21, q: "Identify the Roman province where the Spanish language developed.", o: ["Britannia", "Hispania", "Italia", "Aegyptus"], a: 1, cat: "Geography", expl: "Spanish comes from the Latin spoken in <strong>Hispania</strong> (Spain)." },
    { id: 22, q: "What legendary Trojan led refugees from Troy to Italy?", o: ["Aeneas", "Achilles", "Hector", "Romulus"], a: 0, cat: "History", expl: "<strong>Aeneas</strong> fled Troy and his descendants founded Rome." },
    { id: 23, q: "What area was NOT physically connected to the Roman Empire by land?", o: ["Hispania", "Britannia", "Germania", "Gallia"], a: 1, cat: "Geography", expl: "<strong>Britannia</strong> (Britain) is an island." },
    { id: 24, q: "When sailors circumnavigate an island, they sail:", o: ["across it", "around it", "through it", "under it"], a: 1, cat: "Geography", expl: "Circum = around; Navigare = to sail." },
    { id: 25, q: "The star on the map indicates what city located on the Tiber River?", o: ["Athēnae", "Alexandrīa", "Londīnium", "Rōma"], a: 3, cat: "Geography", expl: "<strong>Rome</strong> is founded on the banks of the Tiber River." },
    { id: 26, q: "In which Roman province was the Nile River located?", o: ["Britannia", "Germania", "Aegyptus", "Gallia"], a: 2, cat: "Geography", expl: "The Nile River is in <strong>Aegyptus</strong> (Egypt)." },
    { id: 27, q: "The eruption of what volcano buried the city of Pompeii?", o: ["Etna", "Olympus", "Ida", "Vesuvius"], a: 3, cat: "Geography", expl: "<strong>Mt. Vesuvius</strong> erupted in 79 AD, burying Pompeii." },
    { id: 28, q: "If a bird flew in a straight line from Hispania (Spain) to Graecia (Greece), it would be flying:", o: ["north", "south", "east", "west"], a: 2, cat: "Geography", expl: "Greece is to the <strong>East</strong> of Spain." },

    // DERIVATIVES
    { id: 29, q: "Meaning of Latin root in nominate, nominal, and denominator?", o: ["name", "choice", "night", "calendar"], a: 0, cat: "Derivatives", expl: "From the Latin word <strong>nomen</strong> (name)." },
    { id: 30, q: "Based on Latin roots, what would you study in culinary school?", o: ["astronomy", "cooking", "architecture", "engineering"], a: 1, cat: "Derivatives", expl: "From <strong>culina</strong> (kitchen)." },
    { id: 31, q: "Vitality, vitamin, and revitalize are related to the Latin word for _____.", o: ["light", "size", "journey", "life"], a: 3, cat: "Derivatives", expl: "From <strong>vita</strong> (life)." },
    { id: 32, q: "Based on Latin roots, what word means 'under the sea'?", o: ["subterranean", "submarine", "subscription", "suburban"], a: 1, cat: "Derivatives", expl: "Sub = under; Mare = sea." },
    { id: 33, q: "The tourists amble along the path. Amble means:", o: ["run", "laugh", "sit", "walk"], a: 3, cat: "Derivatives", expl: "From <strong>ambulare</strong> (to walk)." },
    { id: 34, q: "Spain's Canary Islands had a large number of _____.", o: ["horses", "dogs", "pigs", "snakes"], a: 1, cat: "Derivatives", expl: "Canary comes from <strong>canis</strong> (dog)." },
    { id: 35, q: "According to its Latin root, a 'multi-unit' structure has:", o: ["small units", "square units", "many units", "empty units"], a: 2, cat: "Derivatives", expl: "Multus = many." },
    { id: 36, q: "Stellar, solar, and lunar describe objects found where?", o: ["in caelo", "in silvā", "in rīvō", "in forō"], a: 0, cat: "Derivatives", expl: "They are in the sky (<strong>in caelo</strong>). Stella=Star, Sol=Sun, Luna=Moon." },
    { id: 37, q: "October, octet, and octave are related to the Latin word for:", o: ["eye", "ocean", "eight", "music"], a: 2, cat: "Derivatives", expl: "From <strong>octo</strong> (eight)." },
    { id: 38, q: "Based on its Latin root, a constellation is a group of:", o: ["birds", "islands", "stars", "ships"], a: 2, cat: "Derivatives", expl: "From <strong>stella</strong> (star)." },
    { id: 39, q: "Fabulous, fable, and fib are related to the Latin word for a:", o: ["story", "spectacle", "valuable object", "library"], a: 0, cat: "Derivatives", expl: "From <strong>fabula</strong> (story)." },
    { id: 40, q: "Students attend a naval institute to learn about:", o: ["anatomy", "agriculture", "sculpting", "ships"], a: 3, cat: "Derivatives", expl: "From <strong>navis</strong> (ship)." },
    { id: 41, q: "Based on the word's Latin root, a portable device is easy to:", o: ["carry", "throw", "find", "use"], a: 0, cat: "Derivatives", expl: "From <strong>portare</strong> (to carry)." },
    { id: 42, q: "Audible comes from the Latin verb meaning to:", o: ["see", "hear", "write", "read"], a: 1, cat: "Derivatives", expl: "From <strong>audire</strong> (to hear)." },
    { id: 43, q: "The concert was magnificent. The root magnus means:", o: ["long", "great", "crowded", "boring"], a: 1, cat: "Derivatives", expl: "From <strong>magnus</strong> (great/big)." },
    { id: 44, q: "The teacher said, 'That's a novel idea!' Novel means:", o: ["wise", "bad", "dangerous", "new"], a: 3, cat: "Derivatives", expl: "From <strong>novus</strong> (new)." },
    { id: 45, q: "Based on the Latin root (urbs), who would be considered urbane?", o: ["a sailor", "a city dweller", "a shepherd", "a nymph"], a: 1, cat: "Derivatives", expl: "From <strong>urbs</strong> (city). Urbane means sophisticated." },
    { id: 46, q: "The malevolent king lived in a castle. Malevolent means:", o: ["old", "wise", "faithful", "evil"], a: 3, cat: "Derivatives", expl: "Male = bad; Volo = wish. Wishing evil." },

    // DAILY LIFE / CULTURE
    { id: 47, q: "Name for the covered walkway surrounding the garden in a Roman vīlla?", o: ["cubiculum", "lātrīna", "tablīnum", "peristylium"], a: 3, cat: "Daily Life", expl: "The <strong>peristylium</strong> is the columned porch around the garden." },
    { id: 48, q: "Which word does NOT refer to an article of clothing?", o: ["stola", "toga", "sōl", "tunica"], a: 2, cat: "Daily Life", expl: "<strong>Sōl</strong> means Sun. The others are clothes." },
    { id: 49, q: "What is prepared in the culīna and served in the trīclīnium?", o: ["toga", "cēna", "taberna", "pecūnia"], a: 1, cat: "Daily Life", expl: "<strong>Cēna</strong> (dinner). Culina is kitchen, Triclinium is dining room." },
    { id: 50, q: "Which word fits best: equus, lupus, fēles, _____?", o: ["canis", "cibus", "lūdus", "gladius"], a: 0, cat: "Daily Life", expl: "This is a list of animals: Horse, Wolf, Cat, <strong>Dog</strong> (Canis)." },
    { id: 51, q: "Which word fits best: cubiculum, hortus, culīna, _____?", o: ["amīcus", "ātrium", "māter", "stella"], a: 1, cat: "Daily Life", expl: "This is a list of rooms. <strong>Atrium</strong> is the main hall." },
    { id: 52, q: "What did a Roman call multi-level apartment buildings?", o: ["insulae", "fora", "templa", "thermae"], a: 0, cat: "Daily Life", expl: "<strong>Insulae</strong> (islands) were apartment blocks." },
    { id: 53, q: "What was the paterfamilias in charge of?", o: ["the household", "the government", "the army", "the gladiator school"], a: 0, cat: "Culture", expl: "The <strong>paterfamilias</strong> was the male head of the household." },
    { id: 54, q: "Which word fits best: toga, tunica, _____, palla?", o: ["stola", "via", "cubiculum", "filius"], a: 0, cat: "Daily Life", expl: "These are clothes. <strong>Stola</strong> is a woman's dress." },
    { id: 55, q: "Most popular location for chariot racing in Rome?", o: ["Colosseum", "Circus Maximus", "Forum", "Pantheon"], a: 1, cat: "Culture", expl: "The <strong>Circus Maximus</strong> was the race track." },
    { id: 56, q: "Common piece of clothing worn by all Romans?", o: ["taberna", "fenestra", "tunica", "hōra"], a: 2, cat: "Daily Life", expl: "The <strong>tunica</strong> (tunic) was the basic shirt." },
    { id: 57, q: "An ātrium, a cubiculum, and a tablīnum are found:", o: ["in vīllā", "in silvā", "in agrō", "in amphitheātrō"], a: 0, cat: "Daily Life", expl: "In a house (<strong>in vīllā</strong>)." },
    { id: 58, q: "Where in ancient Rome would you find an atrium?", o: ["on the road", "in a house", "in a forum", "in a harbor"], a: 1, cat: "Daily Life", expl: "The atrium is the main room <strong>in a house</strong>." },
    { id: 59, q: "What was a common occurrence at the Colosseum?", o: ["poetry performances", "gladiatorial fights", "cold baths", "diplomatic meetings"], a: 1, cat: "Culture", expl: "The Colosseum was for <strong>gladiator fights</strong>." },
    { id: 60, q: "What animal played a major part at the Circus Maximus?", o: ["elephantus", "equus", "ursus", "leō"], a: 1, cat: "Culture", expl: "Chariot races used horses (<strong>equus</strong>)." },
    { id: 61, q: "A Roman woman would often wear a _____ over her stola.", o: ["tunica", "solea", "toga", "palla"], a: 3, cat: "Daily Life", expl: "The <strong>palla</strong> was a wrap/shawl." },
    { id: 62, q: "It's time for bed! Where would the father and mother sleep?", o: ["in cubiculō", "in vestibulō", "in tablīnō", "in culīnā"], a: 0, cat: "Daily Life", expl: "In the bedroom (<strong>in cubiculō</strong>)." },
    { id: 63, q: "Where would a Roman buy new sandals?", o: ["in tabernā", "in cūriā", "in vīllā rūsticā", "in templō"], a: 0, cat: "Daily Life", expl: "In a shop (<strong>in tabernā</strong>)." },
    { id: 64, q: "Who in ancient Rome wore a toga praetexta?", o: ["senator", "mater", "libertus", "servus"], a: 0, cat: "Culture", expl: "<strong>Senators</strong> wore the toga with a purple border." },
    { id: 65, q: "Where would Romans watch gladiatorial fights?", o: ["the Forum", "the Curia", "the Colosseum", "the Pantheon"], a: 2, cat: "Culture", expl: "The <strong>Colosseum</strong>." },

    // PHRASES
    { id: 66, q: "Meaning of abbreviation 'etc.' (et cetera)?", o: ["and the rest", "that is", "for example", "or similar"], a: 0, cat: "Phrases", expl: "Et = and; Cetera = the rest." },
    { id: 67, q: "Which expression is a warning against unwanted visitors?", o: ["carpe diem", "tempus fugit", "ante merīdiem", "cavē canem"], a: 3, cat: "Phrases", expl: "<strong>Cavē canem</strong> means 'Beware of the dog'." },
    { id: 68, q: "Why use 'P.S.' (post scriptum) in an email?", o: ["to greet", "to add something after", "to introduce subject", "to provide example"], a: 1, cat: "Phrases", expl: "Post = after; Scriptum = written." },
    { id: 69, q: "What does 'Meā culpā' mean?", o: ["They are admitting a mistake", "It is the end of class", "New assignment", "Partner work"], a: 0, cat: "Phrases", expl: "It means 'My fault' or 'My blame'." },
    { id: 70, q: "What does a.m. (ante meridiem) mean?", o: ["It's on a boat", "It's before noon", "It's at your house", "It's after dinner"], a: 1, cat: "Phrases", expl: "Ante = before; Meridiem = midday." },
    { id: 71, q: "Why would a worker receive a 'bonus'?", o: ["Their work was late", "Their work was average", "Their work needed correction", "Their work was good"], a: 3, cat: "Phrases", expl: "Bonus means <strong>good</strong>." },
    { id: 72, q: "Which phrase encourages someone to hurry?", o: ["cum laude", "e pluribus unum", "nota bene", "tempus fugit"], a: 3, cat: "Phrases", expl: "<strong>Tempus fugit</strong> means 'Time flies'." },
    { id: 73, q: "When a list ends with etc., it indicates that:", o: ["the list is very important", "the list is complete", "there are more items", "the last item is incorrect"], a: 2, cat: "Phrases", expl: "It means 'and the rest', implying more items exist." },
    { id: 74, q: "Abbreviation meaning 'pay close attention'?", o: ["N.B.", "a.m.", "etc.", "P.S."], a: 0, cat: "Phrases", expl: "<strong>N.B.</strong> (Nota Bene) means 'Note Well'." },
    { id: 75, q: "Latin for 'out of many, one' (USA Motto)?", o: ["excelsior", "carpe diem", "in deo speramus", "e pluribus unum"], a: 3, cat: "Phrases", expl: "<strong>E pluribus unum</strong>." },
    { id: 76, q: "Encouragement to live a full life:", o: ["Minimē", "Ē plūribus ūnum", "Tacēte!", "Carpe diem!"], a: 3, cat: "Phrases", expl: "<strong>Carpe diem</strong> means 'Seize the day'." },
    { id: 77, q: "Phrase seen in an announcement of death?", o: ["ab urbe conditā", "mare nostrum", "festīnā lentē", "in memoriam"], a: 3, cat: "Phrases", expl: "<strong>In memoriam</strong> means 'In memory of'." },
    { id: 78, q: "Translation of 'festīnā lentē'?", o: ["hurry slowly", "happy birthday", "time flies", "seize the day"], a: 0, cat: "Phrases", expl: "It is an oxymoron: 'Make haste slowly' (hurry slowly)." },

    // SPOKEN / NUMERALS
    { id: 79, q: "Teacher asks 'Quis abest'. What do they want to know?", o: ["What is your name?", "What day is it?", "Who is absent?", "How are you feeling?"], a: 2, cat: "Spoken Latin", expl: "Quis = Who; Abest = Is absent." },
    { id: 80, q: "Quot avēs sunt? (Image shows 3 birds)", o: ["trēs", "quīnque", "septem", "novem"], a: 0, cat: "Numerals", expl: "<strong>Trēs</strong> = Three." },
    { id: 81, q: "III et IV sunt _____.", o: ["VI", "VII", "VIII", "IX"], a: 1, cat: "Numerals", expl: "3 (III) + 4 (IV) = 7 (<strong>VII</strong>)." },
    { id: 82, q: "Teacher calls your name. Correct response?", o: ["Adsum!", "Abest!", "Valē!", "Minimē!"], a: 0, cat: "Spoken Latin", expl: "<strong>Adsum</strong> means 'I am here' (present)." },
    { id: 83, q: "Fīlius respondet, '_____, ad Colosseum ambulō.' (Negative response)", o: ["Salvēte", "Minimē", "Nihil est", "Grātiās vōbīs"], a: 1, cat: "Spoken Latin", expl: "<strong>Minimē</strong> means 'No' or 'Not at all'." },
    { id: 84, q: "What should you say when leaving a group of friends?", o: ["Cūr?", "Quot?", "Salvē!", "Valēte!"], a: 3, cat: "Spoken Latin", expl: "<strong>Valēte</strong> is 'Goodbye' to multiple people." },
    { id: 85, q: "Solve: V - I =", o: ["III", "IV", "VI", "IX"], a: 1, cat: "Numerals", expl: "5 (V) - 1 (I) = 4 (<strong>IV</strong>)." },
    { id: 86, q: "Were you alive in ancient Rome? (Answer in Latin)", o: ["Quis est?", "Valēte!", "Salvē!", "Minimē."], a: 3, cat: "Spoken Latin", expl: "<strong>Minimē</strong> (No)." },
    { id: 87, q: "What is the opposite of 'Minimē'?", o: ["Salvē", "Ita", "Ante", "Nōn"], a: 1, cat: "Spoken Latin", expl: "The opposite of No is Yes (<strong>Ita</strong>)." },
    { id: 88, q: "Sequence: I, III, V, _____, IX.", o: ["II", "IV", "VII", "VIII"], a: 2, cat: "Numerals", expl: "1, 3, 5, <strong>7 (VII)</strong>, 9. Odd numbers." },
    { id: 89, q: "Response to 'Quid agis?' (How are you?)", o: ["Ubi?", "Quot?", "Bene!", "Valēte!"], a: 2, cat: "Spoken Latin", expl: "<strong>Bene</strong> means 'Well'." },
    { id: 90, q: "Which numeral is the largest?", o: ["IX", "III", "V", "VIII"], a: 0, cat: "Numerals", expl: "IX = 9 (Largest). V=5, VIII=8, III=3." },
    { id: 91, q: "How to greet two people (Antonia and Aula)?", o: ["Salvē!", "Valē!", "Salvēte!", "Valēte!"], a: 2, cat: "Spoken Latin", expl: "<strong>Salvēte</strong> is Hello to plural people." },
    { id: 92, q: "A teacher asking your name would say:", o: ["Quid est nōmen tibi?", "Suntne laetī?", "Quota hōra est?", "Ubi sunt discipulī?"], a: 0, cat: "Spoken Latin", expl: "Literally: 'What is the name to you?'" }
];